# Numpy Practice Jupyter Notebook


### Basics

In [2]:
import numpy as np

In [3]:
# Dimension ItemSize Type TotalSize
a1 = np.array([[1,2],[2,3],[3,4]])
print(a1.ndim," ",a1.itemsize," ",a1.dtype," ",a1.nbytes)

2   4   int32   24


In [50]:
x1 = np.array([[1,2],[2,3],[3,4]],dtype=complex)

In [51]:
x1

array([[ 1.+0.j,  2.+0.j],
       [ 2.+0.j,  3.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [9]:
# Zero Matrix
zero = np.zeros((3,4))
print(zero)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [10]:
# Size Shape
print(zero.size," ",zero.shape)

12   (3, 4)


In [11]:
a1.reshape(2,3)
print(a1)
print(zero)

[[1 2]
 [2 3]
 [3 4]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [12]:
a1+a1
print(a1)

[[1 2]
 [2 3]
 [3 4]]


In [ ]:
a1+a1
# (+ - * / **) 
# Mathematical Functions

In [83]:
np.sqrt(a1)
#np.std(a1)
#sandara deviation
#Square root

array([[ 1.        ,  1.73205081],
       [ 1.73205081,  1.41421356],
       [ 1.73205081,  1.        ]])

In [18]:
a1.sum(axis=0)


array([6, 9])

In [32]:
a1.max()
#max min sum sin cos etc.

4

In [20]:
# indexing
a1[0,0]

1

In [7]:
#a1[:,1]=3
a1[:,1]=[3,2,1]
print(a1)

[[1 3]
 [3 2]
 [3 1]]


In [51]:
a1[1,0] = 3
a1 = a1.astype('float64')
print(a1)

[[ 1.  3.]
 [ 3.  2.]
 [ 3.  1.]]


In [56]:
# indexing through list
a1[[1,2]]

array([[ 3.,  2.],
       [ 3.,  1.]])

In [23]:
a1[0:2,1]
#step can be given at third place => [start:end:step]

array([2, 3])

In [47]:
# Stacking matrices
b1 = np.arange(6).reshape(3,2)

In [48]:
c1 = np.arange(6,12).reshape(3,2)

In [50]:
np.vstack((b1,c1,b1))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [30]:
np.hstack((b1,c1))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [34]:
# Splitting Matrices
d1 = np.arange(30).reshape(2,15)

In [35]:
d1


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [43]:
res1 = np.vsplit(d1,2)

In [45]:
res1[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [46]:
res2 = np.hsplit(d1,3)

In [49]:
res2[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [52]:
# Boolean Indexing
y = a1 > 3

In [53]:
y

array([[False, False],
       [False, False],
       [False,  True]], dtype=bool)

In [53]:
a1[a1>1]
#a1[y]

array([ 3.,  3.,  2.,  3.])

In [55]:
a1[y] = 3

In [56]:
a1

array([[1, 2],
       [2, 3],
       [3, 3]])

In [57]:
a = np.arange(12).reshape(3,4)

In [58]:
# Looping through elements
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [59]:
for elem in a.flatten():
    print(elem)

0
1
2
3
4
5
6
7
8
9
10
11


In [60]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [62]:
for x in np.nditer(a, order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [64]:
a2 = np.arange(3,15,4).reshape(3,1)

In [65]:
for x,y in np.nditer([a,a2]):
    print(x,y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


In [67]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...] = x*x

In [69]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [8]:
# 3 dimensional array
arr = np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
print(arr)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [14]:
# indexing 3 dimensional array
arr[1,1,2]

11

In [24]:
np.full((2,2),2)

C:\Users\HP\Anaconda3\lib\site-packages\numpy\core\numeric.py:294: FutureWarning: in the future, full((2, 2), 2) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 2.,  2.],
       [ 2.,  2.]])

In [25]:
np.full_like(a1,5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [26]:
# random number between 0 and 1
np.random.rand(4,2)

array([[ 0.43813838,  0.47095825],
       [ 0.3853595 ,  0.54128715],
       [ 0.42411764,  0.34572396],
       [ 0.25329192,  0.45523847]])

In [28]:
# random number below 7
np.random.randint(7,size=(3,3))

array([[3, 5, 0],
       [6, 5, 4],
       [0, 2, 2]])

In [29]:
#identity matrix
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [37]:
out = np.ones((5,5))
out[1:4,1:4] = 0
out[2,2] = 9
print(out)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  9.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [39]:
# copying array
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)


[1 2 3]


In [43]:
#multiplication
a = np.ones((2,3))
b = np.full((3,2),2)
np.matmul(a,b)

C:\Users\HP\Anaconda3\lib\site-packages\numpy\core\numeric.py:294: FutureWarning: in the future, full((3, 2), 2) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 6.,  6.],
       [ 6.,  6.]])

In [45]:
# determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [61]:
a1

array([[ 1.,  3.],
       [ 3.,  2.],
       [ 3.,  1.]])

In [65]:
np.any(a1>2,axis=1)

array([ True,  True,  True], dtype=bool)

In [66]:
np.all(a1>1,axis=0)

array([False, False], dtype=bool)

In [67]:
np.all(a1>0,axis=0)

array([ True,  True], dtype=bool)

In [73]:
# Some more indexing
z = np.arange(1,31).reshape(6,5)
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [70]:
z[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [75]:
z[(z%2 == 0) & (z <= 20)]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [80]:
z[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [81]:
z[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])